# Generated by Django 4.1.7 on 2023-03-30 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measerement_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measerement',
            name='senser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurement.senser'),
        ),
    ]
